### PR TITLE
notification are now generalized from prayers to events

### PR DESCRIPTION
**Pull request by ssi-anik**

### CODE REVIEW

**Comment by me-shaon** [comment]
Is creating Python 2 dependency necessary here?

**Comment by thedevsaddam** [comment]
I think Python 2 is not necessary

**Comment by ssi-anik** [comment]
the dependency of python 2 was not necessary. But, you always have the python2 in your machine.

**Comment by me-shaon** [comment]
Yeah, that's true, But having an available replacement by a single line code, i don't think it is wise to add that dependency and imposing a version dependency in the doc.

**Pull request merged**
