### PR TITLE
unnecessary requirements file removed and README file updated

### PR DESCRIPTION
**Pull request by me-shaon**

### CODE REVIEW

**Comment by thedevsaddam** [comment]
I have already made the changes. @me-shaon thank you :)

**Comment by me-shaon** [comment]
Great. No problem. :)

**Comment by me-shaon** [comment]
Do we really need that requirements.txt file though? It's just one line command, right?

**Comment by thedevsaddam** [comment]
No we don't need this file.

**Comment by thedevsaddam** [comment]
Merged the PR @me-shaon

**Pull request merged**
